version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: jobportal-backend
    ports:
      - "3606:3606"
    depends_on:
      - postgres
    environment:
      - PORT=3606
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=job_portal_db

  browsing-jobs:
    build: ./browsing-jobs
    container_name: jobportal-browsing
    ports:
      - "8611:80"
    depends_on:
      - backend

  hr-side-posting:
    build: ./hr-side-posting
    container_name: jobportal-hr
    ports:
      - "8612:80"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    container_name: jobportal-postgres
    ports:
      - "5606:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: job_portal_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:

